#!/usr/bin/env bash

# sync files with syncthing
# syncthing cli config options --help | rg  relays # use it to find about available options
sudo pacman -S --noconfirm syncthing
systemctl --user enable --now syncthing.service
syncthing cli config options relays-enabled set false
syncthing cli config options natenabled set false
syncthing cli config options global-ann-enabled set false
syncthing cli config options crenabled set false
syncthing cli config options auto-upgrade-intervalh set 0
syncthing cli config options releases-url set ""
# syncthing cli config options uraccepted set -1

# create sync directories
mkdir ~/dev
mkdir ~/dev-0
mkdir ~/.obsidian-vault
mkdir ~/.backups
ln -snf ~/dotfiles/scripts/syncthing/.stignore_dev ~/dev/.stignore
ln -snf ~/dotfiles/scripts/syncthing/.stignore_dev ~/dev-0/.stignore

ln -snf ~/dotfiles/scripts/rsync/.rsyncignore_dev ~/dev/.rsyncignore

ln -snf ~/dotfiles/scripts/rclone/.rclone-filters-dev.txt ~/dev/.rclone-filters.txt

# visit for tuning options
# https://docs.syncthing.net/users/tuning.html
