#!/usr/bin/env bash

# sudo ufw app list -> displays all apps
# sudo ufw limit SSH  -> instead of using sudo ufw allow SSH
sudo pacman -S --noconfirm ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow nothing in, everything out
sudo ufw deny SSH
sudo ufw allow syncthing

# Allow Docker containers to use DNS on host
sudo ufw allow in proto udp from 172.16.0.0/12 to 172.17.0.1 port 53 comment 'allow-docker-dns'

sudo ufw --force enable
sudo systemctl enable ufw.service

# Turn on Docker protections
sudo ufw-docker install
sudo ufw reload
