#!/usr/bin/env bash

# hyprpicker -> to pick colors from screen using pastel pick and other tools
# waybar -> menu bar
# mako - notification
# nwg-look - theming gtk apps
# screensharing and file picking - xdg-desktop-portal-hyprland
# polkit for app authentication
sudo pacman -S --noconfirm  \
    hyprland \
    ttf-font-awesome \
    uwsm \
    brightnessctl \
    hyprpicker \
    waybar \
    mako \
    hyprlock \
    hypridle \
    hyprpaper \
    nwg-look gnome-themes-extra \
    xdg-desktop-portal-hyprland \
    hyprsunset \
    hyprpolkitagent



# rofi and application launcher
# pavucontrol - volume control
sudo pacman -S --noconfirm \
    rofi \
    rofi-emoji \
    rofi-calc \
    pavucontrol

systemctl --user enable waybar.service # menu
systemctl --user enable mako.service # notification
systemctl --user enable hypridle.service # lock screen
systemctl --user enable hyprpaper.service # wallpaper
systemctl --user enable xdg-desktop-portal-hyprland  # screensharing and file picking
systemctl --user enable hyprsunset.service  # hyprsunset for blue light filtering
systemctl --user enable hyprpolkitagent.service
systemctl --user enable gcr-ssh-agent.service # enable gcr for ssh keys management

# qt
# sudo pacman -Syu qt5-wayland qt6-wayland --noconfirm
