[projects."/home/jehad/test/worktrunk"]
approved-commands = [
    '[ -n "$TMUX" ] && tmux rename-window {{branch | sanitize}}',
    """[ -n "$TMUX" ] && tmux rename-window {{ (repo ~ '-' ~ branch) | sanitize}}""",
    "wt step copy-ignored",
    "[ -f mise.toml ] && mise trust",
    "[ -f mise.toml ] && mise install",
]

[projects."github.com/mamacrm/frontend"]
approved-commands = [
    "npm run format_check",
    "npm run check",
    "npm run lint",
    "npm run build",
    "mise run blc",
]
