skip-commit-generation-prompt = true

# blocking, complete before post start
[post-create]
copy = 'wt step copy-ignored'

[post-start]
mise-trust = '[ -f mise.toml ] && mise trust'

[post-switch]
tmux = "[ -n \"$TMUX\" ] && tmux rename-window {{ (repo ~ '-' ~ branch) | sanitize}}"
# mise-install = '[ -f mise.toml ] && mise install'

[commit.generation]
command = "aichat -m gemini:gemini-2.5-flash"

[list]
summary = true
