# This is a default config file for bottom.

[flags]
basic = true
battery = true
process_memory_as_value = true
enable_cache_memory = true

[styles.cpu]
all_entry_color = "#575279"
avg_entry_color = "#56949f"
cpu_core_colors = ["#b4637a","#ea9d34","#286983","#56949f","#907aa9","#d7827e"]
[styles.memory]
ram_color = "#56949f"
cache_color = "#b4637a"
swap_color = "#ea9d34"
gpu_colors = ["#907aa9","#d7827e","#b4637a","#ea9d34","#286983","#56949f"]
arc_color = "#d7827e"
[styles.network]
rx_color = "#56949f"
tx_color = "#b4637a"
rx_total_color = "#d7827e"
tx_total_color = "#56949f"
[styles.battery]
high_battery_color = "#56949f"
medium_battery_color = "#ea9d34"
low_battery_color = "#b4637a"
[styles.tables]
headers = {color = "#575279"}
[styles.graphs]
graph_color = "#9893a5"
legend_text = {color = "#9893a5"}
[styles.widgets]
border_color = "#9893a5"
selected_border_color = "#56949f"
widget_title = {color = "#575279"}
text = {color = "#575279"}
selected_text = {color = "#faf4ed", bg_color = "#56949f"}
disabled_text = {color = "#9893a5"}
