#!/usr/bin/env bash

# mise use -g uv
# mise use -g bun deno node@lts pnpm
mise use -g node@lts pnpm
# mise use -g lazygit
mise use -g opencode
mise use -g npm:@kilocode/cli
mise use -g npm:@fission-ai/openspec@latest
