#!/usr/bin/env bash

# mise use -g uv
# mise use -g bun deno node@lts pnpm
mise use -g node@lts go pnpm
mise use -g npm:@kilocode/cli claude npm:@fission-ai/openspec@latest opencode
mise use -g worktrunk lazygit
# neovim
mise use -g npm:fallow
mise install just
