# This is a default config file for bottom.

[flags]
basic = true
battery = true
process_memory_as_value = true
enable_cache_memory = true

[styles.cpu]
all_entry_color = "#a89984"
avg_entry_color = "#d65d0e"
cpu_core_colors = ["#cc241d","#d79921","#98971a","#458588","#b16286","#689d6a"]
[styles.memory]
ram_color = "#458588"
cache_color = "#cc241d"
swap_color = "#d79921"
gpu_colors = ["#b16286","#689d6a","#cc241d","#d79921","#98971a","#458588"]
arc_color = "#689d6a"
[styles.network]
rx_color = "#458588"
tx_color = "#cc241d"
rx_total_color = "#689d6a"
tx_total_color = "#458588"
[styles.battery]
high_battery_color = "#458588"
medium_battery_color = "#d79921"
low_battery_color = "#cc241d"
[styles.tables]
headers = {color = "#a89984"}
[styles.graphs]
graph_color = "#928374"
legend_text = {color = "#928374"}
[styles.widgets]
border_color = "#928374"
selected_border_color = "#d65d0e"
widget_title = {color = "#a89984"}
text = {color = "#a89984"}
selected_text = {color = "#282828", bg_color = "#d65d0e"}
disabled_text = {color = "#928374"}
