# This is a default config file for bottom.

[flags]
basic = true
battery = true
process_memory_as_value = true
enable_cache_memory = true

[styles.cpu]
all_entry_color = "#bac2de"
avg_entry_color = "#89b4fa"
cpu_core_colors = ["#f38ba8","#f9e2af","#a6e3a1","#89b4fa","#f5c2e7","#94e2d5"]
[styles.memory]
ram_color = "#89b4fa"
cache_color = "#f38ba8"
swap_color = "#f9e2af"
gpu_colors = ["#f5c2e7","#94e2d5","#f38ba8","#f9e2af","#a6e3a1","#89b4fa"]
arc_color = "#94e2d5"
[styles.network]
rx_color = "#89b4fa"
tx_color = "#f38ba8"
rx_total_color = "#94e2d5"
tx_total_color = "#89b4fa"
[styles.battery]
high_battery_color = "#89b4fa"
medium_battery_color = "#f9e2af"
low_battery_color = "#f38ba8"
[styles.tables]
headers = {color = "#bac2de"}
[styles.graphs]
graph_color = "#585b70"
legend_text = {color = "#585b70"}
[styles.widgets]
border_color = "#585b70"
selected_border_color = "#89b4fa"
widget_title = {color = "#bac2de"}
text = {color = "#bac2de"}
selected_text = {color = "#1e1e2e", bg_color = "#89b4fa"}
disabled_text = {color = "#585b70"}
