#!/usr/bin/env bash

# ni -> install package
ni() {
   if [ -f package-lock.json ]; then
      npm install "$@"
   elif [ -f bun.lock ]; then
      bun install "$@"
   elif [ -f pnpm-lock.yaml ]; then
      pnpm install "$@"
   else
      pnpm install "$@"
   fi
}

# nu -> update package
nu() {
   if [ -f package-lock.json ]; then
      npm update "$@"
   elif [ -f bun.lock ]; then
      bun update "$@"
   elif [ -f pnpm-lock.yaml ]; then
      pnpm update "$@"
   else
      pnpm update "$@"
   fi
}

# nr -> remove package
nrm() {
   if [ -f package-lock.json ]; then
      npm uninstall "$@"
   elif [ -f bun.lock ]; then
      bun remove "$@"
   elif [ -f pnpm-lock.yaml ]; then
      pnpm remove "$@"
   else
      pnpm remove "$@"
   fi
}

if [ -f package-lock.json ]; then
   alias npm='npm'
elif [ -f bun.lock ]; then
   alias npm='bun'
elif [ -f pnpm-lock.yaml ]; then
   alias npm='pnpm'
else
   alias npm='pnpm'
fi

alias node-package-manager='npm'
