#!/usr/bin/env bash

# ni -> install package
ni() {
    if [ -f package-lock.json ]; then
        npm install "$@"
    elif [ -f bun.lock ]; then
        bun install "$@"
    elif [ -f pnpm-lock.yaml ]; then
        pnpm install "$@"
    else
        pnpm install "$@"
    fi
}

# nu -> update package
nu() {
    if [ -f package-lock.json ]; then
        npm update "$@"
    elif [ -f bun.lock ]; then
        bun update "$@"
    elif [ -f pnpm-lock.yaml ]; then
        pnpm update "$@"
    else
        pnpm update "$@"
    fi
}

# nr -> remove package
nrm() {
    if [ -f package-lock.json ]; then
        npm uninstall "$@"
    elif [ -f bun.lock ]; then
        bun remove "$@"
    elif [ -f pnpm-lock.yaml ]; then
        pnpm remove "$@"
    else
        pnpm remove "$@"
    fi
}

npm() {
    if [ -f package-lock.json ]; then
        command npm "$@"
    elif [ -f bun.lock ]; then
        bun "$@"
    elif [ -f pnpm-lock.yaml ]; then
        pnpm "$@"
    else
        pnpm "$@"
    fi
}

nrd() {
    if [ -f package-lock.json ]; then
        npm run dev
    elif [ -f bun.lock ]; then
        bun run dev
    elif [ -f pnpm-lock.yaml ]; then
        pnpm run dev
    else
        pnpm run dev
    fi
}

nr() {
    if [ -f package-lock.json ]; then
        npm run "$@"
    elif [ -f bun.lock ]; then
        bun run "$@"
    elif [ -f pnpm-lock.yaml ]; then
        pnpm run "$@"
    else
        pnpm run "$@"
    fi
}
