#!/usr/env/bin bash

# global aliases
alias -g NE='2>/dev/null'      # null error
alias -g DN='> /dev/null'      # pipe standard output to /dev/null
alias -g NUL='>/dev/null 2>&1' # pipe standard output and error to /dev/null

# promodoro
declare -A pomo_options
pomo_options["work"]="60"
pomo_options["typing"]="11"
pomo_options["break"]="10"

pomodoro() {
   if [ -n "$1" -a -n "${pomo_options["$1"]}" ]; then
      val=$1
      # echo $val | lolcat
      timer ${pomo_options["$val"]}m
      # spd-say "'$val' session done"
      notify-send "'$val' session done"
   fi
}

# Suffix aliases
suffix_alias_if_command bat md bat
suffix_alias_if_command open mov open
suffix_alias_if_command open png open
suffix_alias_if_command open mp4 open
suffix_alias_if_command bat yaml 'bat -l yaml'
suffix_alias_if_command bat json 'bat -l json'

if [[ -n ${EDITOR:-} ]] && commands_available "${EDITOR%% *}"; then
    alias -s "go=$EDITOR"
    alias -s "js=$EDITOR"
    alias -s "ts=$EDITOR"
fi

# Command-backed global aliases
global_alias_if_command wl-copy 'C' '| wl-copy'
global_alias_if_command wl-paste 'P' 'wl-paste'
global_alias_if_command less 'L' '| less'

if commands_available go-timer notify-send; then
    alias work="pomodoro 'work'"
    alias typing="pomodoro 'typing'"
    alias break="pomodoro 'break'"
fi
