#!/usr/env/bin bash

# suffix aliases
alias -s md="bat"
alias -s mov="open"
alias -s png="open"
alias -s mp4="open"
alias -s go="$EDITOR"
alias -s js="$EDITOR"
alias -s ts="$EDITOR"
alias -s yaml="bat -l yaml"
alias -s json="bat -l json"

# global aliases
alias -g NE='2>/dev/null'      # null error
alias -g DN='> /dev/null'      # pipe standard output to /dev/null
alias -g NUL='>/dev/null 2>&1' # pipe standard output and error to /dev/null
alias -g C='| wl-copy'
alias -g P='wl-paste'
alias -g L='| less'

# keybindings
openZellij() {
   # zellij <$TTY
   df-zellij-f
   zle redisplay
}
zle -N openZellij
bindkey "^z" openZellij

function current_dir() {
   local current_dir=$PWD
   if [[ $current_dir == $HOME ]]; then
      current_dir="~"
   else
      current_dir=${current_dir##*/}
   fi

   echo $current_dir
}

function change_tab_title() {
   local title=$1
   command nohup zellij action rename-tab $title >/dev/null 2>&1
}

function set_tab_to_working_dir() {
   local result=$?
   local title=$(current_dir)
   # uncomment the following to show the exit code after a failed command
   # if [[ $result -gt 0 ]]; then
   #     title="$title [$result]"
   # fi

   change_tab_title $title
}

# function set_tab_to_command_line() {
#     local cmdline=$1
#     change_tab_title $cmdline
# }

if [[ -n $ZELLIJ ]]; then
   add-zsh-hook precmd set_tab_to_working_dir
   # add-zsh-hook preexec set_tab_to_command_line
fi

# promodoro
declare -A pomo_options
pomo_options["work"]="60"
pomo_options["typing"]="11"
pomo_options["break"]="10"

pomodoro() {
   if [ -n "$1" -a -n "${pomo_options["$1"]}" ]; then
      val=$1
      # echo $val | lolcat
      timer ${pomo_options["$val"]}m
      # spd-say "'$val' session done"
      notify-send "'$val' session done"
   fi
}
alias work="pomodoro 'work'"
alias typing="pomodoro 'typing'"
alias break="pomodoro 'break'"
