#!/usr/env/bin bash

# suffix aliases
alias -s md="bat"
alias -s mov="open"
alias -s png="open"
alias -s mp4="open"
alias -s go="$EDITOR"
alias -s js="$EDITOR"
alias -s ts="$EDITOR"
alias -s yaml="bat -l yaml"
alias -s json="bat -l json"

# global aliases
alias -g NE='2>/dev/null'      # null error
alias -g DN='> /dev/null'      # pipe standard output to /dev/null
alias -g NUL='>/dev/null 2>&1' # pipe standard output and error to /dev/null
alias -g C='| wl-copy'
alias -g P='wl-paste'
alias -g L='| less'
