#!/usr/bin/env bash

DOTFILES="${DOTFILES:-$HOME/dotfiles}"
cd "$DOTFILES"

mkdir -p ~/.config
ln -snf "$DOTFILES/git/.config/git" ~/.config/git
# ln -snf "$DOTFILES/lazygit/.config/lazygit" ~/.config/lazygit
ln -snf "$DOTFILES/opencode/.config/opencode" ~/.config/opencode
ln -snf "$DOTFILES/kilo/.config/kilo" ~/.config/kilo
ln -snf "$DOTFILES/agents/.agents" ~/.agents
ln -snf ~/dotfiles/opencode/.config/opencode ~/.kilocode
mkdir -p ~/.kilocode/skills # correct path, after symlink
ln -snf ~/.agents/skills/* ~/.kilocode/skills/

# stow mise
mkdir -p ~/.config/mise
cp ~/dotfiles/mise/.config/mise/config.toml ~/.config/mise/config.toml

mkdir -p ~/.claude
ln -snf ~/dotfiles/.claude/settings.json ~/.claude/settings.json

rm -rf ~/.bashrc
ln -snf ~/dotfiles/bash/.bashrc ~/.bashrc
ln -snf ~/dotfiles/zsh/.config/zsh ~/.config/zsh
ln -snf ~/dotfiles/zsh/.zshenv ~/.zshenv

mkdir -p ~/.claude/skills

ln -snf ~/dotfiles/.claude/settings.json ~/.claude/settings.json
ln -snf ~/dotfiles/.claude/statusline-command.sh ~/.claude/statusline-command.sh
ln -snf ~/.agents/skills/* ~/.claude/skills/
