#!/usr/bin/env bash

# mise use -g uv
# mise use -g bun deno node@lts pnpm
mise use -g npm:@kilocode/cli claude npm:@fission-ai/openspec@latest opencode
mise use -g aqua:max-sixty/worktrunk lazygit
mise use -g go pnpm node@lts
mise install just
