#!/usr/bin/env bash

# mise use -g uv
# mise use -g bun deno node@lts pnpm
mise use -g npm:@kilocode/cli claude npm:@fission-ai/openspec@latest opencode
mise use -g worktrunk lazygit
mise use -g go pnpm node@lts neovim
mise install just
