#!/usr/bin/env bash

# roo code cli
curl -fsSL https://raw.githubusercontent.com/RooCodeInc/Roo-Code/main/apps/cli/install.sh | sh

# not working cpu type othe than host
mise use -g uv

uv tool install mistral-vibe
uv tool install openhands --python 3.12
# uv tool install --force --python python3.12 --with pip aider-chat@latest # not working

mise use -g opencode
mise use -g npm:@kilocode/cli
mise use -g gemini
# mise use -g npm:@continuedev/cli # cn # doesn't work

# mise use -g github:antinomyhq/forge # no available free models
# mise use -g github:MoonshotAI/kimi-cli # no free models
mise use -g github:github/copilot-cli

mise use -g github:JetBrains/junie # cli by jetbrains
# junie [<options>] [<task>]
# cd you-project-folder
# junie "Fix the bug in MyClass"

# mise use -g github:Aider-AI/aider # no matching assets only provides source code

mise use -g npm:@qwen-code/qwen-code
mise use -g npm:cline

mise use -g bun deno node@lts pnpm
mise use -g lazygit

# setup syncthing directories
# mkdir ~/dev
# ln -snf ~/dotfiles/scripts/syncthing/.stignore_dev ~/dev/.stignore
