# This is a default config file for bottom.

[flags]
basic = true
battery = true
process_memory_as_value = true
enable_cache_memory = true

[styles.cpu]
all_entry_color = "#e6d9db"
avg_entry_color = "#f38d70"
cpu_core_colors = ["#fd6883","#f9cc6c","#adda78","#f38d70","#a8a9eb","#85dacc"]
[styles.memory]
ram_color = "#f38d70"
cache_color = "#fd6883"
swap_color = "#f9cc6c"
gpu_colors = ["#a8a9eb","#85dacc","#fd6883","#f9cc6c","#adda78","#f38d70"]
arc_color = "#85dacc"
[styles.network]
rx_color = "#f38d70"
tx_color = "#fd6883"
rx_total_color = "#85dacc"
tx_total_color = "#f38d70"
[styles.battery]
high_battery_color = "#f38d70"
medium_battery_color = "#f9cc6c"
low_battery_color = "#fd6883"
[styles.tables]
headers = {color = "#e6d9db"}
[styles.graphs]
graph_color = "#948a8b"
legend_text = {color = "#948a8b"}
[styles.widgets]
border_color = "#948a8b"
selected_border_color = "#f38d70"
widget_title = {color = "#e6d9db"}
text = {color = "#e6d9db"}
selected_text = {color = "#2c2525", bg_color = "#f38d70"}
disabled_text = {color = "#948a8b"}
