#!/usr/bin/env bash

# crush by bubble tea
# sudo mkdir -p /etc/apt/keyrings
# curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
# echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
# sudo apt update && sudo apt install crush

# not working cpu type othe than host
mise use -g uv
mise use -g bun deno node@lts pnpm
mise use -g lazygit

mise use -g opencode
mise use -g npm:@kilocode/cli
mise use -g npm:cline
mise use -g gemini
mise use -g npm:btca # better context engine by bendevis
mise use -g aichat   # use any model in terminal, also used in automations
# Set up btca for this project: scan package.json for major dependencies (frameworks, libraries, tools), suggest adding each as a btca resource with sensible defaults, then create a btca.config.jsonc file in the project root and update AGENTS.md with usage instructions. Ask me to confirm each resource before adding.
mise use -g npm:@qwen-code/qwen-code

gemini extensions install https://github.com/obra/superpowers
qwen extensions install https://github.com/obra/superpowers

# uv tool install mistral-vibe
# uv tool install openhands --python 3.12
# uv tool install --force --python python3.12 --with pip aider-chat@latest # doesn't work with git index version 3

# mise use -g npm:@continuedev/cli # cn # doesn't work

# mise use -g github:antinomyhq/forge # no available free models
# mise use -g github:MoonshotAI/kimi-cli # no free models
# mise use -g github:github/copilot-cli

# mise use -g github:JetBrains/junie # cli by jetbrains
# junie [<options>] [<task>]
# cd you-project-folder
# junie "Fix the bug in MyClass"

# mise use -g github:Aider-AI/aider # no matching assets only provides source code

# mise use -g npm:@augmentcode/auggie@latest # no free plan but has one of the best context engine
# mise use -g npm:codebuff # has free plan and ads

# TODO: research more about pi (it seems to be good)
# mise use -g npm:@mariozechner/pi-coding-agent # signup not working, redirect broken # need to research more

# roo code cli
# curl -fsSL https://raw.githubusercontent.com/RooCodeInc/Roo-Code/main/apps/cli/install.sh | sh

# mise use -g t3
