#!/usr/bin/env bash

# upgrade and install stow
sudo pacman -Syu --noconfirm stow

# setup additional application icons
mkdir -p $HOME/.local/share/applications/icons
ln -snf ~/dotfiles/setup/applications/icons $HOME/.local/share/applications
# ln -snf ~/dotfiles/devcontainers/dev/.devcontainer $HOME/dev/base-setup/.devcontainer
# cp ~/dotfiles/devcontainers/dev/.devcontainer $HOME/dev/base-setup -r

# stow
~/dotfiles/scripts/stow/stow-base
~/dotfiles/scripts/stow/stow-hyprland

# theme
~/dotfiles/setup/arch-hyprland/theme

# gnome theme
~/dotfiles/setup/arch-hyprland/gnome-theme

# setup package managers (yay, flatpak, mise)
~/dotfiles/setup/arch-hyprland/setup-omarchy-repos
~/dotfiles/setup/arch-hyprland/setup-packages/setup-flatpak
~/dotfiles/setup/arch-hyprland/setup-packages/setup-mise
~/dotfiles/setup/arch-hyprland/setup-packages/setup-yay

# install packages
~/dotfiles/setup/arch-hyprland/packages/pacman-packages
~/dotfiles/setup/arch-hyprland/packages/yay-packages
~/dotfiles/setup/arch-hyprland/packages/flatpak-packages
~/dotfiles/setup/arch-hyprland/packages/mise-packages

# setup hyprland
~/dotfiles/setup/arch-hyprland/setup-packages/setup-hyprland
~/dotfiles/setup/arch-hyprland/setup-packages/setup-walker

# setup docker
~/dotfiles/setup/arch-hyprland/setup-packages/setup-docker

# setup syncthing
~/dotfiles/setup/arch-hyprland/setup-packages/setup-syncthing

# ufw setup
~/dotfiles/setup/arch-hyprland/setup-packages/setup-ufw

# zsh setup
~/dotfiles/setup/arch-hyprland/setup-packages/setup-zsh

# app armor
~/dotfiles/setup/arch-hyprland/setup-packages/setup-apparmor

# script for setting up kanata on arch linux
~/dotfiles/setup/arch-hyprland/setup-packages/setup-kanata

# github cli
# ~/dotfiles/setup/arch-hyprland/setup-packages/setup-github-cli

# additional
~/dotfiles/setup/arch-hyprland/setup-packages/additional-packages

# go packages
~/dotfiles/setup/arch-hyprland/packages/go-packages

# create keyring
~/dotfiles/setup/arch-hyprland/keyring

# performance optimization for laptop (tlp)
~/dotfiles/setup/arch-hyprland/setup-packages/setup-tlp

# create useful directories
mkdir -p ~/dev
mkdir -p ~/dev-0
mkdir -p ~/.obsidian-vault

# update grub-btrfsd if setuped disk with encryption for snapper backup to work properly
# sudo env EDITOR=nvim systemctl edit --full grub-btrfsd # no need to do anything for snapper
# enable gdm
sudo pacman -S --noconfirm gdm
sudo systemctl enable gdm.service
tldr --update

# To test if AppArmor has been correctly enabled:
echo "Is app armor enabled: $(aa-enabled)"
echo "make sure to run this # ~/dotfiles/setup/arch-hyprland/setup-packages/setup-github-cli
after gh auth login"

echo "Do you want to restart? [y/N] "
read -r response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    shutdown -r now
fi
