#!/usr/bin/env bash

tldr --update

# Test if AppArmor is correctly enabled.
echo "Is app armor enabled: $(aa-enabled 2>/dev/null || echo 'unknown')"
echo "make sure to run this # ~/dotfiles/setup/arch-hyprland/setup-packages/setup-github-cli after gh auth login"

if command -v gum &>/dev/null && [[ -t 1 ]]; then
    if gum confirm "Restart now?"; then
        sudo shutdown -r now
    fi
else
    echo "Do you want to restart? [y/N] "
    read -r response
    if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
        sudo shutdown -r now
    fi
fi
