#!/usr/bin/env bash

ln -snf ~/.config/themes/kanagawa ~/.config/theme
# ln -snf ~/.config/omarchy/current/theme/backgrounds/1-scenery-pink-lakeside-sunset-lake-landscape-scenic-panorama-7680x3215-144.png ~/.config/omarchy/current/background

# Set specific app links for current theme
ln -snf ~/.config/theme/neovim.lua ~/.config/nvim/lua/plugins/theme.lua

# bottom theme
mkdir -p ~/.config/bottom
ln -snf ~/.config/theme/bottom.toml ~/.config/bottom/bottom.toml

mkdir -p ~/.config/mako
ln -snf ~/.config/theme/mako.ini ~/.config/mako/config

mkdir -p ~/.config/eza
ln -snf ~/.config/theme/eza.yml ~/.config/eza/theme.yml

# Add managed policy directories for Chromium and Brave for theme changes
sudo mkdir -p /etc/chromium/policies/managed
sudo chmod a+rw /etc/chromium/policies/managed

sudo mkdir -p /etc/brave/policies/managed
sudo chmod a+rw /etc/brave/policies/managed
