#!/usr/bin/env bash

# shellcheck source=../../common/pacman-lib
. "$(dirname "${BASH_SOURCE[0]}")/../../common/pacman-lib"

pacman_install apparmor

# update /etc/default/grup GRUB_CMDLINE_LINUX_DEFAULT and append this options lsm=landlock,lockdown,yama,integrity,apparmor,bpf
sudo sed -i 's/^\(GRUB_CMDLINE_LINUX_DEFAULT="[^"]*\)"/\1 lsm=landlock,lockdown,yama,integrity,apparmor,bpf"/' /etc/default/grub

sudo grub-mkconfig -o /boot/grub/grub.cfg
sudo systemctl enable apparmor.service

# To test if AppArmor has been correctly enabled:
echo  "Is app armor enabled: $(aa-enabled)"
