#!/usr/bin/env bash

# shellcheck source=../../common/pacman-lib
. "$(dirname "${BASH_SOURCE[0]}")/../../common/pacman-lib"

pacman_install bluez bluez-utils bluetui
sudo systemctl enable --now bluetooth.service
