#!/usr/bin/env bash

set -euo pipefail

sudo pacman -S --noconfirm --needed syncthing

syncthing generate >/dev/null 2>&1 || true
systemctl --user enable --now syncthing.service

for _ in {1..30}; do
    if syncthing cli config options relays-enabled get &>/dev/null; then
        break
    fi
    sleep 1
done

syncthing cli config options relays-enabled set false
syncthing cli config options natenabled set false
syncthing cli config options global-ann-enabled set false
syncthing cli config options crenabled set false
syncthing cli config options auto-upgrade-intervalh set 0
syncthing cli config options releases-url set ""
