#!/usr/bin/env bash

set -e

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../common/ufw-lib
. "$HERE/../../common/ufw-lib"

ufw_bootstrap

# Allow nothing in, everything out
sudo ufw deny SSH

ufw_commit
