# This is a default config file for bottom.

[flags]
basic = true
battery = true
process_memory_as_value = true
enable_cache_memory = true

[styles.cpu]
all_entry_color = "#c8c093"
avg_entry_color = "#7e9cd8"
cpu_core_colors = ["#c34043","#c0a36e","#76946a","#7e9cd8","#957fb8","#6a9589"]
[styles.memory]
ram_color = "#7e9cd8"
cache_color = "#c34043"
swap_color = "#c0a36e"
gpu_colors = ["#957fb8","#6a9589","#c34043","#c0a36e","#76946a","#7e9cd8"]
arc_color = "#6a9589"
[styles.network]
rx_color = "#7e9cd8"
tx_color = "#c34043"
rx_total_color = "#6a9589"
tx_total_color = "#7e9cd8"
[styles.battery]
high_battery_color = "#7e9cd8"
medium_battery_color = "#c0a36e"
low_battery_color = "#c34043"
[styles.tables]
headers = {color = "#c8c093"}
[styles.graphs]
graph_color = "#727169"
legend_text = {color = "#727169"}
[styles.widgets]
border_color = "#727169"
selected_border_color = "#7e9cd8"
widget_title = {color = "#c8c093"}
text = {color = "#c8c093"}
selected_text = {color = "#1f1f28", bg_color = "#7e9cd8"}
disabled_text = {color = "#727169"}
