$rosewater = rgb(f2ecbc)
$rosewaterAlpha = f2ecbc

$flamingo = rgb(d9a594)
$flamingoAlpha = d9a594

$pink = rgb(D27E99)
$pinkAlpha = D27E99

$mauve = rgb(b8b4d0)
$mauveAlpha = b8b4d0

$red = rgb(E46876)
$redAlpha = E46876

$maroon = rgb(FF5D62)
$maroonAlpha = FF5D62

$peach = rgb(FFA066)
$peachAlpha = FFA066

$yellow = rgb(E6C384)
$yellowAlpha = E6C384

$green = rgb(98BB6C)
$greenAlpha = 98BB6C

$teal = rgb(7AA89F)
$tealAlpha = 7AA89F

$sky = rgb(7FB4CA)
$skyAlpha = 7FB4CA

$sapphire = rgb(A3D4D5)
$sapphireAlpha = A3D4D5

$blue = rgb(7E9CD8)
$blueAlpha = 7E9CD8

$lavender = rgb(957FB8)
$lavenderAlpha = 957FB8

$text = rgb(DCD7BA)
$textAlpha = DCD7BA

$subtext1 = rgb(C8C093)
$subtext1Alpha = C8C093

$subtext0 = rgb(727169)
$subtext0Alpha = 727169

$overlay2 = rgb(717C7C)
$overlay2Alpha = 717C7C

$overlay1 = rgb(54546D)
$overlay1Alpha = 54546D

$overlay0 = rgb(545464)
$overlay0Alpha = 545464

$surface2 = rgb(223249)
$surface2Alpha = 223249

$surface1 = rgb(2D4F67)
$surface1Alpha = 2D4F67

$surface0 = rgb(2A2A37)
$surface0Alpha = 2A2A37

$base = rgb(1F1F28)
$baseAlpha = 1F1F28

$mantle = rgb(181820)
$mantleAlpha = 181820

$crust = rgb(16161D)
$crustAlpha = 16161D
