$color = rgba(1f1f28, 1.0)
$colorAlpha = rgba(1f1f28, 0.8)
$inner_color = rgba(1f1f28, 0.8)
$inner_colorAlpha = rgba(1f1f28, 0.6)
$outer_color = rgba(dcd7ba, 1.0)
$outer_colorAlpha = rgba(dcd7ba, 0.8)
$font_color = rgba(dcd7ba, 1.0)
$font_colorAlpha = rgba(dcd7ba, 0.8)
$check_color = rgba(7e9cd8, 1.0)
