preload = ~/.config/backgrounds/Fuji-Dark.png
wallpaper = , ~/.config/backgrounds/Fuji-Dark.png
# preload = ~/.config/backgrounds/solid-catppuccin-mocha-bg.png
# wallpaper = , ~/.config/backgrounds/solid-catppuccin-mocha-bg.png
