################
### MONITORS ###
################
source =~/.config/hypr/conf/monitors.conf

#################
### AUTOSTART ###
#################
source =~/.config/hypr/conf/autostart.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################
source =~/.config/hypr/conf/envs.conf

#####################
### LOOK AND FEEL ###
#####################
source =~/.config/hypr/conf/look_and_feel.conf

#############
### INPUT ###
#############
source =~/.config/hypr/conf/input.conf

###################
### MY PROGRAMS ###
###################
source =~/.config/hypr/conf/my_programs.conf

###################
### KEYBINDINGS ###
###################
source =~/.config/hypr/conf/keybindings.conf
source =~/.config/hypr/bindings/utilities.conf
source =~/.config/hypr/bindings/clipboard.conf
source =~/.config/hypr/bindings/media.conf
source =~/.config/hypr/bindings/tiling.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################
source =~/.config/hypr/conf/windows_and_workspaces.conf


##############
### OTHERS ###
##############
ecosystem {
    no_update_news= true
}

#### theme
source = ~/.config/theme/hyprland.conf


# App-specific tweaks
source = ~/.config/hypr/conf/apps.conf
