################
### MONITORS ###
################
source =~/.config/hypr/conf/monitors.conf

#################
### AUTOSTART ###
#################
source =~/.config/hypr/conf/autostart.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

#####################
### LOOK AND FEEL ###
#####################
source =~/.config/hypr/conf/look_and_feel.conf

#############
### INPUT ###
#############
source =~/.config/hypr/conf/input.conf

###################
### MY PROGRAMS ###
###################
source =~/.config/hypr/conf/my_programs.conf

###################
### KEYBINDINGS ###
###################
source =~/.config/hypr/conf/keybindings.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################
source =~/.config/hypr/conf/windows_and_workspaces.conf


##############
### OTHERS ###
##############
ecosystem {
    no_update_news= true
}

#### theme
source = ~/.config/theme/hyprland.conf
