# configuration {
    background = FF181820
    base = FF1F1F28
    text = FFDCD7BA
    alternate_base = FF2A2A37
    bright_text = FFC8C093
    accent = FF957FB8
    accent_secondary = FF7FB4CA
    h1_size = 19
    h2_size = 15
    h3_size = 13
    font_size = 11
    small_font_size = 10
    icon_theme = ""
# }
