# This is a default config file for bottom.

[flags]
basic = true
battery = true
process_memory_as_value = true
enable_cache_memory = true

[styles.cpu]
all_entry_color = "#787c99"
avg_entry_color = "#7aa2f7"
cpu_core_colors = ["#f7768e","#e0af68","#9ece6a","#7aa2f7","#ad8ee6","#449dab"]
[styles.memory]
ram_color = "#7aa2f7"
cache_color = "#f7768e"
swap_color = "#e0af68"
gpu_colors = ["#ad8ee6","#449dab","#f7768e","#e0af68","#9ece6a","#7aa2f7"]
arc_color = "#449dab"
[styles.network]
rx_color = "#7aa2f7"
tx_color = "#f7768e"
rx_total_color = "#449dab"
tx_total_color = "#7aa2f7"
[styles.battery]
high_battery_color = "#7aa2f7"
medium_battery_color = "#e0af68"
low_battery_color = "#f7768e"
[styles.tables]
headers = {color = "#787c99"}
[styles.graphs]
graph_color = "#444b6a"
legend_text = {color = "#444b6a"}
[styles.widgets]
border_color = "#444b6a"
selected_border_color = "#7aa2f7"
widget_title = {color = "#787c99"}
text = {color = "#787c99"}
selected_text = {color = "#1a1b26", bg_color = "#7aa2f7"}
disabled_text = {color = "#444b6a"}
