#!/usr/bin/env bash

# stow
cd ~/dotfiles

stow git
mkdir -p ~/.config/opencode
ln -snf ~/dotfiles/opencode/.config/opencode/agent ~/.config/opencode/agent
ln -snf ~/dotfiles/opencode/.config/opencode/command ~/.config/opencode/command
ln -snf ~/dotfiles/opencode/.config/opencode/plugin ~/.config/opencode/plugin
ln -snf ~/dotfiles/opencode/.config/opencode/AGENTS.md ~/.config/opencode/AGENTS.md
ln -snf ~/dotfiles/opencode/.config/opencode/opencode.jsonc ~/.config/opencode/opencode.jsonc
ln -snf ~/dotfiles/opencode/.config/opencode/tui.json ~/.config/opencode/tui.json
stow agents
stow tmux
stow zsh # to get the aliasrc file
rm -rf ~/.bashrc
stow bash
mkdir -p ~/.config/mise
cp ~/dotfiles/mise/.config/mise/config.toml ~/.config/mise/config.toml

mkdir -p ~/dev-0
mkdir -p ~/.kilocode
ln -snf ~/dotfiles/kilocode/.kilocode/kilo.jsonc ~/.kilocode/kilo.jsonc
ln -snf ~/dotfiles/kilocode/.kilocode/plugin ~/.kilocode/plugin
ln -snf ~/dotfiles/kilocode/.kilocode/agent ~/.kilocode/agent
ln -snf ~/dotfiles/kilocode/.kilocode/command ~/.kilocode/command
ln -snf ~/dotfiles/kilocode/.kilocode/AGENTS.md ~/.kilocode/AGENTS.md
mkdir -p ~/.kilocode/skills
ln -snf ~/.agents/skills/* ~/.kilocode/skills/

mise use -g usage

echo "now logout and log back in"
