#!/usr/bin/env bash

~/dotfiles/setup/alpine/setup-ufw

mise use -g bun deno node@lts node@20.12 pnpm
mise use -g uv lazygit

mise use -g opencode github:Kilo-Org/kilo npm:cline
mise use -g gemini npm:@qwen-code/qwen-code
mise use -g npm:btca

# roo code cli
curl -fsSL https://raw.githubusercontent.com/RooCodeInc/Roo-Code/main/apps/cli/install.sh | sh
