# This is a default config file for bottom.

[flags]
basic = true
battery = true
process_memory_as_value = true
enable_cache_memory = true

[styles.cpu]
all_entry_color = "#5c5f77"
avg_entry_color = "#1e66f5"
cpu_core_colors = ["#d20f39","#df8e1d","#40a02b","#1e66f5","#ea76cb","#179299"]
[styles.memory]
ram_color = "#1e66f5"
cache_color = "#d20f39"
swap_color = "#df8e1d"
gpu_colors = ["#ea76cb","#179299","#d20f39","#df8e1d","#40a02b","#1e66f5"]
arc_color = "#179299"
[styles.network]
rx_color = "#1e66f5"
tx_color = "#d20f39"
rx_total_color = "#179299"
tx_total_color = "#1e66f5"
[styles.battery]
high_battery_color = "#1e66f5"
medium_battery_color = "#df8e1d"
low_battery_color = "#d20f39"
[styles.tables]
headers = {color = "#5c5f77"}
[styles.graphs]
graph_color = "#acb0be"
legend_text = {color = "#acb0be"}
[styles.widgets]
border_color = "#acb0be"
selected_border_color = "#1e66f5"
widget_title = {color = "#5c5f77"}
text = {color = "#5c5f77"}
selected_text = {color = "#eff1f5", bg_color = "#1e66f5"}
disabled_text = {color = "#acb0be"}
