#!/usr/bin/env bash

# Center new windows in the middle of the screen
gsettings set org.gnome.mutter center-new-windows true

# Reveal week numbers in the Gnome calendar
gsettings set org.gnome.desktop.calendar show-weekdate true

# nautilus
# default list-view
gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'
