#!/usr/bin/env bash

sudo apt install -y incus
sudo usermod -aG incus-admin $USER
newgrp incus-admin # reload the current shell
# create network
incus network create incusbr0
incus profile device add default eth0 nic network=incusbr0 name=eth0
incus network set incusbr0 ipv4.address auto
# create storage pool
incus profile device add default root disk path=/ pool=default
incus storage create default dir
# incus profile show default

##### update firewalld
# Add incusbr0 to the trusted zone:
sudo firewall-cmd --permanent --zone=trusted --add-interface=incusbr0
# Then allow IP masquerading so containers can reach the outside:
sudo firewall-cmd --permanent --zone=trusted --add-masquerade
sudo firewall-cmd --reload

wget https://github.com/mensfeld/code-on-incus/releases/download/v0.7.0/coi-linux-amd64
chmod +x coi-linux-amd64
sudo mv coi-linux-amd64 /usr/local/bin/coi
coi build --force # Rebuild image with new features
# coi setup         # First-time setup (if new install)
