#!/usr/bin/env bash

sudo apt update -y
sudo apt upgrade -y

sudo apt install stow -y
~/dotfiles/setup/ubuntu-server/stow

~/dotfiles/setup/ubuntu-server/packages

# comment mise from .zshrc and ohters
sed -i 's|^eval "\$(mise activate zsh)"|# &|' ~/.config/zsh/.zshrc
sed -i 's|^[[:space:]]*source "\$XDG_CONFIG_HOME/zsh/ni"|# &|' ~/.config/zsh/.zshrc
sed -i 's|^[[:space:]]*source "\$XDG_CONFIG_HOME/zsh/new-worktree"|# &|' ~/.config/zsh/.zshrc
sed -i 's|^[[:space:]]*export CONTEXT7_API_KEY="\$(pass env/context7_api_key)"|# &|' ~/.zshenv
sed -i 's|^[[:space:]]*export BROWSER_USE_API_KEY="\$(pass env/browser_use_test)"|# &|' ~/.zshenv
sed -i 's|^[[:space:]]*export MISE_GITHUB_TOKEN=\$(pass github/personal-access-token-mise)|# &|' ~/.zshenv


sudo install -d -m755 -o $(id -u) -g $(id -g) /nix
curl -L https://nixos.org/nix/install | sh
source $HOME/.nix-profile/etc/profile.d/nix.sh

nix-env -iA nixpkgs.procs
nix-env -iA nixpkgs.starship
nix-env -iA nixpkgs.fastfetch
nix-env -iA nixpkgs.fzf
nix-env -iA nixpkgs.bat



chsh -s $(which zsh)


~/dotfiles/setup/ubuntu-server/rm-snap


echo "now logout and log back in"
