#!/usr/bin/env bash

~/dotfiles/setup/ubuntu-server/setup-ufw

# not working cpu type othe than host
mise use -g bun deno node@lts node@20.12 pnpm
# sudo apt install lazygit # replace with this after ubuntu 25.10
mise use -g uv lazygit

mise use -g opencode github:Kilo-Org/kilo npm:cline
mise use -g gemini npm:@qwen-code/qwen-code
mise use -g npm:btca # better context engine by bendevis

# roo code cli
curl -fsSL https://raw.githubusercontent.com/RooCodeInc/Roo-Code/main/apps/cli/install.sh | sh

# mise use -g t3 # waiting for t3 cli

# prompt for btca
# Set up btca for this project: scan package.json for major dependencies (frameworks, libraries, tools), suggest adding each as a btca resource with sensible defaults, then create a btca.config.jsonc file in the project root and update AGENTS.md with usage instructions. Ask me to confirm each resource before adding.
