#!/usr/bin/env bash

sudo apt update -y
sudo apt upgrade -y
sudo apt install qemu-guest-agent -y
sudo systemctl enable --now qemu-guest-agent.service

sudo apt install stow -y

# stow
cd ~/dotfiles

stow git
stow opencode
stow agents
stow tmux
stow zsh # to get the aliasrc file
rm -rf ~/.bashrc
stow bash

ln -snf ~/dotfiles/opencode/.config/opencode ~/.kilocode
mkdir -p .kilocode/skills
ln -snf ~/.agents/skills/* ~/.kilocode/skills/

# packages
sudo apt install ripgrep git curl zoxide eza bat tealdeer wl-clipboard trash-cli -y
# sudo apt install procs -y # available from ubuntu 25.04

# install the latest version of neovim
sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo apt update
sudo apt install make gcc ripgrep unzip xclip neovim -y

~/dotfiles/setup/ubuntu-server/setup-mise

mise use -g fzf@latest
mise use -g bottom

~/dotfiles/setup/ubuntu-server/rm-snap
git clone https://github.com/nvim-lua/kickstart.nvim.git "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim

echo "now logout and log back in"
