#!/usr/bin/env bash

CREATE_USER=$1

sudo apt update -y
sudo apt upgrade -y
sudo apt install qemu-guest-agent -y
sudo systemctl enable --now qemu-guest-agent.service

# packages
sudo apt install nfs-common stow ripgrep git curl zoxide eza bat tealdeer wl-clipboard trash-cli fzf -y
# sudo apt install procs -y # available from ubuntu 25.04

# install the latest version of neovim
# add-apt-repository not available in lxc
# sudo add-apt-repository ppa:neovim-ppa/unstable -y
# sudo apt update
# sudo apt install make gcc ripgrep unzip xclip neovim -y
sudo apt install make gcc ripgrep unzip xclip -y

# add mise
sudo apt update -y && sudo apt install -y curl
sudo install -dm 755 /etc/apt/keyrings
curl -fSs https://mise.jdx.dev/gpg-key.pub | sudo tee /etc/apt/keyrings/mise-archive-keyring.asc 1>/dev/null
echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.asc] https://mise.jdx.dev/deb stable main" | sudo tee /etc/apt/sources.list.d/mise.list
sudo apt update -y
sudo apt install -y mise

# remove snap
~/dotfiles/setup/ubuntu-server/rm-snap

# add user
if [ -n "$CREATE_USER" ]; then
    useradd -m -s /bin/bash $CREATE_USER
    passwd $CREATE_USER
    # add user to sudoers
    usermod -aG sudo $CREATE_USER
    # allow user to run sudo without password
    echo "$CREATE_USER ALL=(ALL) NOPASSWD:ALL" >/etc/sudoers.d/$CREATE_USER
    chmod 440 /etc/sudoers.d/$CREATE_USER
    visudo -c -f /etc/sudoers.d/$CREATE_USER
    # create ssh keys for user
    mkdir -p /home/$CREATE_USER/.ssh
    cp /root/.ssh/authorized_keys /home/$CREATE_USER/.ssh/authorized_keys
    chown -R $CREATE_USER:$CREATE_USER /home/$CREATE_USER/.ssh
fi

echo "edit vi /etc/ssh/sshd_config"
echo "with this settings"
echo "PermitRootLogin no PasswordAuthentication no"

echo "now logout and log back in"
