#!/usr/bin/env bash

# fzf - version is lower update in ubuntu 26
# bat
sudo apt install ripgrep git curl zsh zoxide eza tealdeer net-tools wl-clipboard -y

# install the latest version of neovim
sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo apt update
sudo apt install make gcc ripgrep unzip git xclip neovim -y
