#!/usr/bin/env bash

~/dotfiles/setup/ubuntu-server/setup-mise
~/dotfiles/setup/ubuntu-server/setup-syncthing
~/dotfiles/setup/ubuntu-server/setup-ufw

# additional tools
mise use -g gemini
mise use -g github:continuedev/continue
mise use -g bun deno node@lts pnpm
mise use -g lazygit



mkdir ~/dev
ln -snf ~/dotfiles/scripts/syncthing/.stignore_dev ~/dev/.stignore
