#!/usr/bin/env bash
# How to setup script
# 1. run "snap list" to list all snap packages installed
# 2. updated the scripts to remove all of them

echo "Removing snapd"
sudo apt remove --autoremove snapd -y

# in order to disable auto installing snap

sudo tee /etc/apt/preferences.d/nosnap.pref >/dev/null <<'EOF'
Package: snapd
Pin: release a=*
Pin-Priority: -10
EOF

sudo apt update -y

echo "Removed snap"
