#!/usr/bin/env bash

~/dotfiles/setup/ubuntu-server/setup-mise
~/dotfiles/setup/ubuntu-server/setup-syncthing
~/dotfiles/setup/ubuntu-server/setup-ufw

# install dev tools
mise use -g bun deno node@lts pnpm
mise use -g lazygit

# setup syncthing share folder
mkdir ~/dev
ln -snf ~/dotfiles/scripts/syncthing/.stignore_dev ~/dev/.stignore
