#!/usr/bin/env bash

if [ -n "$1" ]; then
   if [[ "$1" == *"Start"* ]]; then
      nerd-dictation begin --simulate-input-tool WTYPE --idle-time 0 >/dev/null 2>&1 &
   elif [[ "$1" == *"Stop"* ]]; then
      nerd-dictation end
   fi
   exit 0
fi

if pgrep -f nerd-dictation >/dev/null; then
   echo "Stop nerd-dictation"
else
   echo "Start nerd-dictation"
fi
