#!/usr/bin/env bash

sudo pacman -Syu docker --noconfirm
sudo mkdir -p /etc/docker
echo '{"log-driver":"json-file","log-opts":{"max-size":"10m","max-file":"5"}}' | sudo tee /etc/docker/daemon.json

yay -S --noconfirm docker-desktop

systemctl --user enable docker-desktop
