# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
# exec-once = uwsm app -- mako
# exec-once = ~/.local/bin/dimmer
# exec-once = hyprctl dispatch workspace 1
# exec-once = exec ssh-agent zsh

# exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
