# all monitors
monitor=,preferred,0x0,auto
# monitor=eDP-1,1920x1080,auto,1  # eDP-1
# monitor=HDMI-A-1,preferred,0x0,auto # hdmi-a-1
monitor=DP-1,1920x1080@75,0x0,auto


####################################
# hdmi-a-1 (primary, horizontal)
####################################
# monitor=eDP-1, disable


####################################
# hdmi-a-1 (primary, vertical) & eDP-1 (secondary, vertical)
####################################
# monitor=HDMI-A-1,1920x1080@75,0x0,1
# monitor=eDP-1,1920x1080,auto,1

# ## show workspace 2-10 on monitor hdmi-a-1 (primary)
# workspace= name:2,  monitor:HDMI-A-1
# workspace= name:3,  monitor:HDMI-A-1
# workspace= name:4,  monitor:HDMI-A-1
# workspace= name:5,  monitor:HDMI-A-1
# workspace= name:6,  monitor:HDMI-A-1
# workspace= name:7,  monitor:HDMI-A-1
# workspace= name:8,  monitor:HDMI-A-1
# workspace= name:9,  monitor:HDMI-A-1
# workspace= name:10, monitor:HDMI-A-1

# ## show worspace 1 on monitor eDP-1 (secondary)
# workspace= name:1, monitor:eDP-1


####################################
# hdmi-a-1 (primary, vertical) & eDP-1 (secondary, horizontal)
####################################
monitor=HDMI-A-1,1920x1080@75,0x0,1,transform,1
# monitor=HDMI-A-1,addreserved,200,80,0,0
monitor=HDMI-A-1,addreserved,340,40,0,0
monitor=eDP-1,preferred,1080x860,1

# show workspace 2,4-10 on monitor hdmi-a-1 (primary)
workspace= name:3,  monitor:HDMI-A-1
workspace= name:4,  monitor:HDMI-A-1
workspace= name:5,  monitor:HDMI-A-1
workspace= name:6,  monitor:HDMI-A-1
workspace= name:7,  monitor:HDMI-A-1
workspace= name:8,  monitor:HDMI-A-1
workspace= name:9,  monitor:HDMI-A-1
workspace= name:10, monitor:HDMI-A-1

# show worspace 1,3 on monitor eDP-1 (secondary)
workspace= name:1, monitor:eDP-1
workspace= name:2, monitor:eDP-1

# dp-1
workspace= name:1,  monitor:DP-1
workspace= name:2,  monitor:DP-1
workspace= name:3,  monitor:DP-1
workspace= name:4,  monitor:DP-1
workspace= name:5,  monitor:DP-1
workspace= name:6,  monitor:DP-1
workspace= name:7,  monitor:DP-1
workspace= name:8,  monitor:DP-1
workspace= name:9,  monitor:DP-1
workspace= name:10, monitor:DP-1




############################################
# eDP-1 (primary) & hdmi-a-1 (secondary)
############################################

# show workspace 2-10 on monitor hdmi-a-1 (secondary)
# workspace= name:1, monitor:HDMI-A-1

# show worspace 1 on monitor eDP-1 (primary)
# workspace= name:2, monitor:eDP-1
# workspace= name:3, monitor:eDP-1
# workspace= name:4, monitor:eDP-1
# workspace= name:5, monitor:eDP-1
# workspace= name:6, monitor:eDP-1
# workspace= name:7, monitor:eDP-1
# workspace= name:8, monitor:eDP-1
# workspace= name:9, monitor:eDP-1
# workspace= name:10, monitor:eDP-1
