$terminal = uwsm-app -- ghostty
$menu = uwsm-app -- rofi -show drun
# $browser = uwsm-app -- brave --new-window --ozone-platform=wayland
$browser = uwsm-app -- helium-browser --profile-directory='Profile 2' --new-window --ozone-platform=wayland --ozone-platform-hint=wayland
$webapp = $browser --app
$browser2 = uwsm-app -- brave --new-window --ozone-platform=wayland --ozone-platform-hint=wayland
$webapp2 = $browser2 --app
$browser3 = uwsm-app -- helium-browser --new-window --ozone-platform=wayland --ozone-platform-hint=wayland
$webapp3 = $browser3 --app
