# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1, custom window colors for zed projects
# windowrule = float, ^(kitty)$
# windowrulev2 = bordercolor rgb(A407FF), class:(.*zed.*), title:(.*pro.*)
# windowrulev2 = bordercolor rgb(0000ff), class:(.*zed.*), title:(.*api.*)
# windowrulev2 = bordercolor rgb(00994C), class:(.*zed.*), title:(.*homepage.*)
# windowrulev2 = bordercolor rgb(00994C), class:(.*zed.*), title:(.*me.*)
# windowrulev2 = bordercolor rgb(0066cc), class:(.*zed.*), title:(.*demwell-api.*)
# windowrulev2 = bordercolor rgb(FF03A3), class:(.*zed.*), title:(.*demwell-frontend.*)

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# windowrulev2 = workspace special:zellij, class:^(zellij)$
