# This is a default config file for bottom.

[flags]
basic = true
battery = true
process_memory_as_value = true
enable_cache_memory = true

[styles.cpu]
all_entry_color = "#d3c6aa"
avg_entry_color = "#7fbbb3"
cpu_core_colors = ["#e67e80","#dbbc7f","#a7c080","#7fbbb3","#d699b6","#83c092"]
[styles.memory]
ram_color = "#7fbbb3"
cache_color = "#e67e80"
swap_color = "#dbbc7f"
gpu_colors = ["#d699b6","#83c092","#e67e80","#dbbc7f","#a7c080","#7fbbb3"]
arc_color = "#83c092"
[styles.network]
rx_color = "#7fbbb3"
tx_color = "#e67e80"
rx_total_color = "#83c092"
tx_total_color = "#7fbbb3"
[styles.battery]
high_battery_color = "#7fbbb3"
medium_battery_color = "#dbbc7f"
low_battery_color = "#e67e80"
[styles.tables]
headers = {color = "#d3c6aa"}
[styles.graphs]
graph_color = "#475258"
legend_text = {color = "#475258"}
[styles.widgets]
border_color = "#475258"
selected_border_color = "#7fbbb3"
widget_title = {color = "#d3c6aa"}
text = {color = "#d3c6aa"}
selected_text = {color = "#2d353b", bg_color = "#7fbbb3"}
disabled_text = {color = "#475258"}
